### ISSUE TITLE
serve geojson

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/backend-examplar-2018#1]
if we are to remove postgis dependencies, we will have to:

a. pass through geojson, 
b. serve in a manner which allows for spatial queries,
c. then have to calculate the queries on our own in a tested way
d. and make preforment.

geojson is in the end just json, so passing through json files in itself is not a big challenge, other questions not so sure.

**Comment by znmeb** [comment]
I've posted GeoJSON conversions for all the TriMet shapefiles to our Google Drive if you want some test data.

**Comment by kiniadit** [comment]
just to clarify here - do you mean there will be a api endpoint that serves a static geojson file?

**Comment by bhgrant8** [comment]
@kiniadit, yes that would be the general idea. going to close this ticket out though as out of scope for this examplar repo, but we could move into extensions
