### ISSUE TITLE
no such file or directory: 'requirements.staging.txt'

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#10]
I tried a different path to test out this exemplar - wanted to see what the staging deployment would look like:

```
cp env.sample .env
./bin/build.sh -s
```

It got surprisingly far through the container build, stopping here:

```
Step 14/18 : RUN pip install -r requirements.staging.txt
 ---> Running in d484eda64af8
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.staging.txt'
ERROR: Service 'api_staging' failed to build: The command '/bin/sh -c pip install -r requirements.staging.txt' returned a non-zero code: 1
```

**Comment by bhgrant8** [comment]
yeah, i forgot to change this line to requirements.staging.txt when it copies over to the docker container. Can make the change later today.

i still am copying the development only:

https://github.com/hackoregon/backend-examplar-2018/blob/a3a504338ffb284afb616d96536e7cac88ee9faa/DOCKERFILE.api.staging#L32

A quick note: The reason these are spilt out into individual copying steps is the way docker caches images, upon updates, you will only go back and rebuild to the last level that was changed, so if only the staging requirements change, a new build will not have to go back to the roots requirement step.
See: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#use-a-dockerignore-file for more info

**Comment by bhgrant8** [comment]
closing out as small issue fixed in pr
