### ISSUE TITLE
What's the apt-key command for?

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#11]
Noticed this in the middle of the container build:

```
Step 4/16 : RUN apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
 ---> Running in b43cca33eb0a
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.dXNmqr4t49 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyring /etc/apt/trusted.gpg.d/postgres.gpg --keyserver keys.gnupg.net --recv-key E19F5F87128899B192B1A2C2AD5F960A256A04AF
gpg: requesting key 256A04AF from hkp server keys.gnupg.net
gpg: key 256A04AF: public key "Johannes Ranke (Wissenschaftlicher Berater) <johannes.ranke@jrwb.de>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Removing intermediate container b43cca33eb0a
```

Is this anything to worry about?  Is this coming from a non-standard input file that we maybe shouldn't trust?  I don't remember seeing anything like this before in last year's container builds.

**Comment by znmeb** [comment]
It looks familiar - it might be from one of my scripts / Dockerfiles. Which source file is it in?

**Comment by znmeb** [comment]
Ah - I found it. Yes, it's mine. It's there for the PGDG (PostgreSQL Global Development Group) repositories. See <https://www.postgresql.org/about/news/1432/> for the source.
Let me review the Dockerfiles and see if there's anything else that needs checking. I'm not sure why the API would be running on Debian "jessie".

**Comment by znmeb** [comment]
OK - should I open another issue or just use this one? It looks like the base Python 3.6 image is available for both "jessie" and "stretch" - we may be able to get rid of the PGDG repository if we switch to "stretch".

Do we have a way to test the images if I start working on the Dockerfiles? Something a little more robust than, "Yeah, it builds"

**Comment by bhgrant8** [comment]
So this has been identified, closing with followup on #15 and #16
