### ISSUE TITLE
Remove any Linux components that aren't needed

### ISSUE THREAD

**Issue by znmeb** [hackoregon/backend-examplar-2018#16]
For example, R. The API container should only have enough Linux to run GeoDjango, nothing else.

**Comment by bhgrant8** [comment]
Let's clarify is this for the API or Database? There should be separate issues for each

**Comment by znmeb** [comment]
Yeah - I just noticed that. The database image needs to stay on Jessie but it doesn't need R

**Comment by znmeb** [comment]
The database Dockerfile cleanup is in the pull request. I want to leave this open till I've done the Stretch update, which I won't touch till the pull request is merged.

**Comment by adpeters** [comment]
Is there a reason not to use a pre-existing postgis image like https://github.com/kartoza/docker-postgis or https://github.com/appropriate/docker-postgis? It might be simpler to maintain our own, but could be nice to start from something slightly more standardized too and just add our own minimal changes. Either way the new db dockerfile looks pretty good now.

**Comment by znmeb** [comment]
@adpeters I looked at the existing PostGIS images and they didn't have the level of support that the PostgreSQL image does - it's in the Docker Store, is very well documented and is very flexible and extensible.

**Comment by adpeters** [comment]
Gotcha, that makes sense. Too bad there isn't an official PostGIS image.

**Comment by znmeb** [comment]
All of the OSGeo server-side tools need to be Dockerized; if they gave me a grant I'd probably do it. ;-)

**Comment by znmeb** [comment]
We can close this - the fixes for the database container are in `staging` now. See issue #15 for the API container. I've got that coded but I'm waiting till after we merge the new API creation tools.

**Comment by adpeters** [comment]
Great, closing it.
