### ISSUE TITLE
configure the local database development container

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/backend-examplar-2018#2]
currently the local database development container is based on the postgis container built within the https://github.com/hackoregon/data-science-pet-containers repo. 

I have done some work to remove not api/python dependencies but is this best approach?  what requirements do we have for this repo.

**Comment by MikeTheCanuck** [comment]
I believe that an API definition that isn't tightly coupled to a particular data store makes it easier for folks to create an API that is easier for us to operate, support and troubleshoot.

**Comment by BrianHGrant** [comment]
So, I think the main things we are looking at here is that:

1. This is a development container that is removed at a later point in build process.
2. This should be largely compatible with our eventual deployed database environment. 
3. The one way that may be useful to deviate from 2 is still allowing for postgis if necessary even if we may find alternates in other places.
4. This should be as lightweight amnd minimal as possible to cut down loadtimes and doesn't need data science tools and the like.

Following this pattern, I think looking towards the appropriate/postgis docker container is a great example of a minimal approach to postgis. This builds on top the official postgres container adding a template that can be used for postgis. Not sure about the non-postgis compatibility with our vurrent amazon linux AMI vs the ubuntu imaage i beleive postgres uses but is something that could be tested. Using this container last year I was fairly successful with local dev.

Here is the github repo, we can always use the example, giving credit, while writing our own dockerfiles, not puling image from github

**Comment by znmeb** [comment]
I think this is done - can we close it?

**Comment by adpeters** [comment]
Going along with @MikeTheCanuck's thought, I think it would be nice to emphasize the choices that each project has for a datastore. So we could then point them to a recommended docker image for PostGIS, or a recommended image for simple Postgres (likely just the official Postgres image). The thinking here being that not all projects will necessarily need PostGIS and geodjango. But feel free to correct me on this; maybe we want to start from the assumption that all projects will be using GIS.

**Comment by znmeb** [comment]
So far I know at least Disaster Resilience, Transportation Systems and Neighborhood Development are using GIS in the development / analysis process. As far as I know, all the teams have at least one person capable of doing some GIS analysis - QGIS and geopandas are the two tools I've seen.

We are also forming a documentation team / effort. I don't know about the other teams, but Transportation Systems is using Read the Docs. I'll probably add a "Read the Docs" container to the Data Science Pet Containers repo, but I don't know if it will be part of the stack or a separate container.

**Comment by BrianHGrant** [comment]
To be clear, postgis and geodjango, including drf-gis are extensions on a codebase as opposed to replacements. By this I mean, if you do not create a database with the actual postgis info, the actual db created won't be one even built with the container. Same with the geodjango one. If teams did not make use of it, the code itself will not have dependencies on this and could be removed.

My idea in the design of the container setup is something that would provide examples of patterns that would allow for success and some experimentation by most/all teams, but also allow for configuration of the later stages (staging, travis,...) mainly by devops without a lot of over lap of the code. Using the separate requirements and dockerfiles and the like allows for some of this configuration and experimentation. 

Think though documenting the options is great. It would not be too hard to create a non geodjango image as well, or a flag to say whether to import these or not based on an ARG

**Comment by bhgrant8** [comment]
Closing this out. Question of being able to switch off gis/geodjango dependencies will be followed up in #22
