### ISSUE TITLE
Configuring for 2 environments: Development and Production

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/backend-examplar-2018#25]
Let's hammer out the environments our backend examplar should account for on a basic scaffolding level. This will help to create better documentation and answer a few of the open issues, #24 for example. We may find that we only need to account for two environments, a local dev, and a prod, and potentially an automated testing one or something along those lines.

So who are the users of this repo? 
Which environments will it need to run? 
What are the requirements of each?
What changes need to be made to move from one to another?
What is the easiest way to codify and automate these changes?
Can we combine any environments?

To take a first stab at this I see:

> So who are the users of this repo? 

I see local developers of the API as our first users, DevOps for moving throught the CI/CD pipeline, and our production users of the deployed api

> Which environments will it need to run? 

Locally for development
local staging of how this will work in production (what i call "staging" currently)
travis
testing
cloud staging
cloud production

> What are the requirements of each?

Local developers - need to be able to connect with a localized database. Will want to be able to access debug and testing tools. Be able to run the django dev server for easy reloading of changes and updates in the code. Also be able to run tests in some way

DevOps/Staging - be able to easily/automatically turn off the dev server and run in a production ready environment (gunicorn), be able to remove the local dev db container from the compose, be able to test locally that setup will function before sending to deploy chain, have container build, run tests in the travis builds, sucessfully pass to ecs, and pass healthchecks for service to run as long-running tasks, remain health, not open potential security holes

Production - works in prod, doesn't crash, can connect to a front end (CORS-compliant)

Testing - builds a testing db to connect with and can run tests, runs from a clean environment each time, doesn't take too long to startup (cant spend 10 minutes building container each time you want to run a test)

> What changes need to be made to move from one to another?

Local > Local Staging
remove any debug requirements which are potential security issue
flip Debug to false in python so turns off dev server 
run the gunicorn server command in entrypoint instead of manage.py
connect to a remote database
remove the database container from any compose setup
using appropriate env vars for the staging environment

Local Staging > Travis

I am not sure on this, or if there are any, potentially adding:
 aws-cli and creds if we need to download a project_config.py from s3 or have an ecs_deploy script running from the travis environment (thinking last year's pattern)

Travis > Cloud Staging

This should be automated, so nothing should really be changed at this point. @MikeTheCanuck and i did discuss a travis hook to potentially run the collect static just prior to deploy, to cut down on startup time within the ec2 instance. Does this effect the container config though?

Cloud Staging > Production

Ideally there should not be any, if we do end up using this layer of abstraction

Testing

Not sure how this fits in?

> What is the easiest way to codify and automate these changes?

Currently we have:

.env file container the different layers of variables needed for each environment. this will work for local development and local staging, discussion around how to work with this in the longer term is located in #13 

the bin/build and bin/start scripts which provide a flag to choose the environment. these then run the appropriate docker-compose build or up commands, specifying the proper compose file to choose for environment

docker-compose files then orchestrate the configuration of the containers for the specific environment. Mainly this consists of choosing the correct env variables to pull into each container, whether to use the db container, and which dockerfiles and entrypoint.sh files to run 

DOCKERFILEs for each environment do their thing, including specifying which requirements files to pull into the container and install

entrypoint files then complete any api startup tasks and runs the app in the appropriate server, django's dev server locally and then gunicorn for all other environments

separate test script to run builds and testing commands for different enviornements

> Can we combine any environments?

Probably. I am not sure if any distinctions past the development environment and non-development environments maybe useful, or at least not at this point in development. I may have lead to some confusion by using the moniker "local staging". 

My suggestion is we say maybe we move forward with an approach of two environments:

* development
* production

Until we prove a need for something otherwise.

If folks are in agreement, the other questions would be:

Do we go through and rename all staging related items to production, or leave as is?
Remove the few references to "travis" environment?
How do we configure testing for both.

**Comment by znmeb** [comment]
Testing is pretty easy to add on a local development environment - it's only when we have to deal with secrets and credentials and other AWS cloud phenomena that things get tricky.

Does Django have the notion of "production database" and "development database" as two different connections like Rails does?

**Comment by kiniadit** [comment]
@znmeb Yes, Django can support production vs dev db settings (separate `settings.py` files for each instance)

**Comment by kiniadit** [comment]
@bhgrant8 I'm for the two environment approach. Just production and development should suffice given the scale of this project.

I can't comment on much else on the devops cycle since I don't know enough regarding best practices.

**Comment by znmeb** [comment]
OK - this is merged - closing
