### ISSUE TITLE
Testing Unmanaged Model

### ISSUE THREAD

**Issue by kiniadit** [hackoregon/backend-examplar-2018#26]
If we are going to be testing on an unmanaged db, I propose adding middleware that creates a managed testing db that is created and then destroyed during the test environment. This is what I've done with the transportation API but was wondering if I should add this into the exemplar. Not sure if all projects are following the unmanaged approach.

**Comment by bhgrant8** [comment]
Hey, going to close this issue out, but will be opening up another issue around testing in travis
