### ISSUE TITLE
linking with an example frontend

### ISSUE THREAD

**Issue by BrianHGrant** [hackoregon/backend-examplar-2018#3]
talking with @jaronheard at meeting tonight, a discussion came up with linking an example backend with a example map story card. What do we need to do and serve. This is most likely linked to #1.

**Comment by MikeTheCanuck** [comment]
While this is nice, I can say that for an API developer to reason whether this exemplar works shouldn't have to rely on a web site calling the API - doesn't the Swagger implementation give an API developer the ability to prove to themselves that the Django app is running and serving data from the data store?

**Comment by bhgrant8** [comment]
closing out here as out of scope for the examplar backend
