### ISSUE TITLE
Discussion - do we want an option for a Amazon Linux 2 PostGIS database container?

### ISSUE THREAD

**Issue by znmeb** [hackoregon/backend-examplar-2018#31]
I've got a beta version of the Amazon Linux 2 image with PostGIS from source running in `data-science-pet-containers`. It's going to be a few days before we get all the script wrangling for DevOps to install on AWS, but we have a path forward.

So my questions are:
1. Do we want to add an Amazon Linux 2 with PostGIS database container here?
2. If so, do we want to make it the default?

**Comment by bhgrant8** [comment]
as I understand it, this will add a significant amount of time to initial startup for local development. Would we anticipate later issues, like incompatible database dumps or something similar?

I would like to not complicate the dev environment if we can, however if this becomes a "works on my machine" with hours of downstream complications, then yes, lets update, if not then I would say no.

**Comment by znmeb** [comment]
I'm going to drop this - I have the code for the Amazon Linux 2 container if anyone wants it.
