### ISSUE TITLE
Usage() isn't displaying when running build, start or test scripts on Mac

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#34]
I forgot to add the right parameter to one of the scripts and noticed that the usage text wasn't printing to stdout.  Checked all three scripts  - `/bin/build.sh`, `/bin/start.sh` and `/bin/test.sh` and they're not printing the usage.

I compared to the `/budget_proj/bin/build-proj.sh` output in the `team-budget` repo and that's still working find, and at least at a quick glance I can't see a difference between those scripts that would account for this misbehaviour.

**Comment by bhgrant8** [comment]
apparently, we are missing the check if there are no options entered:

if [ $# == 0 ]; then usage; fi

other wise the getopts loop will return false and just quit:

https://unix.stackexchange.com/questions/50563/how-can-i-detect-that-no-options-were-passed-with-getopts?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by bhgrant8** [comment]
adding the above seems to work, will be updated in my next pr

**Comment by bhgrant8** [comment]
closing as fixed in #35
