### ISSUE TITLE
Script a way to remove the sample db

### ISSUE THREAD

**Issue by bhgrant8** [hackoregon/backend-examplar-2018#4]
Ideally the [remove sample](https://github.com/hackoregon/backend-examplar-2018/blob/staging/bin/remove-sample.sh) script will remove all portions of the sample app. currently the sample database itself will still exist.

Is it possible to start the container, remove the database from the docker container, then stop the container?

**Comment by MikeTheCanuck** [comment]
Is the `remove-sample.sh` meant to be used from the developer's shell in the repo, or called from inside the container after it's been built?

If the former, then perhaps we shouldn't worry about the contents of an already-built container image, but take the cattle-not-pets attitude of "if there's a problem with the container image, destroy it and build a new one".  

I'd suggest we figure out a way to remove whatever automation steps (I haven't looked for it yet, so I'm just guessing) are in the system to create the database during container build-out.

Or even further, just rely on the `project_config.py` to point the app to a proper, already-instantiated database, like we did in last year's API projects?

**Comment by bhgrant8** [comment]
I think we need to be clear on differentiating the local dev environment which makes use of the db container vs. the staging. 

In staging, yes we are ripping out the db container completely and pointing to an already existing database. 

With the local environment, we want to make it easy as possible for the devs to get up and working with potentially a database backup they were given. Not spending alot of time manually configuring a db or local networking between someone's host and a running container is a huge benefit, especially if we are just talking about a sample. 

That being said, the destroy the container and rebuild might be the best option. Really only question is the time to rebuild, but if we just rm the container and not the full image from the local drive, this will probably work.

**Comment by bhgrant8** [comment]
#23 removes the sample db container thus resolving this concern on sample artifacts existing.
