### ISSUE TITLE
Quickstart api image has no Django application users created

### ISSUE THREAD

**Issue by nam20485** [hackoregon/backend-examplar-2018#41]
When the created quickstart application image is run, there is no way to login to the api or the admin interface because there exist no users to login with. We need a method to create the superuser that should be used to log in to the Django application. This can easily be done using the python manage.py createsuperuser command with arguments, but I do not how or what stage of the image build and run process this should be accomplished in.

I am asking about the development images in this case, but we will also need a process to use to create the user we log in to on the production server applications as well. In the development case I believe one possibility might be to add the necessary Django tables and user rows to the database backup so that the user exists after the restore happens.

@znmeb 
@MikeTheCanuck 
@BrianHGrant

**Comment by MikeTheCanuck** [comment]
Yeah it’s probably not clear from what we’ve shared of last year’s projects but none of them used any authentication - all endpoints are public, no user management.

Most of my experience with Django is through Hack Oregon - is it unusual *not* to do user auth with Django apps?

**Comment by nam20485** [comment]
No nevermind that makes sense. My only use case was for some tasks I was performing while creating the disaster-resilience API on top of a generated quickstart application. I was making an assumption that having a user was standard practice and that does not necessarily seem to be a valid assumption now.
I don't think I can justify opening a security hole without being able to articulate a required use case for it being there.

Most of my experience with Django has been with Hack Oregon; my only production experience was running a site on my org's intranet, which had the entire network protected by domain security so having a user and admin interface did not represent as significant of a vulnerability.

Unless anybody objects, I can close this.
