### ISSUE TITLE
production-docker-entrypoint.sh specifies incorrect wsgi application during start.sh -p

### ISSUE THREAD

**Issue by nam20485** [hackoregon/backend-examplar-2018#46]
production-docker-entrypoint.sh contains a line to specify the module to launch as the wsgi application. It is  wrong, a stale reference to the `crash_data_api` Django application from the previous repo this file was copied from. When `startsh.d -p` is used to run the PRODUCTION api docker image, this wsgi application  does not exist and cannot be found so fails.

There should be a `sed` command in the `create-project.sh` script that changes the wsgi application module to whatever Django project name was used to generate the quickstart application. (PROJECT_NAME in .env)

**Comment by znmeb** [comment]
The `sed` is an in-place (`-i`) command so I think you just have to have both files on the single one. I'll fix it tomorrow.

**Comment by znmeb** [comment]
@bhgrant8 Can we do that for the development container too?

**Comment by nam20485** [comment]
> gunicorn $PROJECT_NAME.wsgi -c gunicorn_config.py

@bhgrant8's suggestion has already been merged into the staging branch in  https://github.com/hackoregon/backend-examplar-2018/commit/d8b9762c0e8e141acd377718e6f6195b8bd527c3

The line now looks like:
https://github.com/hackoregon/backend-examplar-2018/blob/b0fa69e2eb245a3a35c5cefe7dc39444a9e1e5cc/bin/production-docker-entrypoint.sh#L11

Closing since this is fixed now.
