### ISSUE TITLE
Always use the verbose version of command-line parameters, where available

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#52]
As I'm reviewing the env var usage from 2017 projects, I noticed that in this script:
https://github.com/hackoregon/team-budget/blob/master/budget_proj/bin/ecs-deploy.sh

you can call command-line parameters as the verbose or compact versions e.g.
- `-c` or `--cluster`
- `-i` or `--image`

When reviewing the usage of command-line parameters in our scripts (and others), I have always found it much more readable to see the expanded version of a parameter than the compact version.

In this particular case, for example, I had always glossed past our usage of these parameters in the [docker-push.sh](https://github.com/hackoregon/team-budget/blob/master/budget_proj/bin/docker-push.sh) script - and never quite felt confident that I knew what that script is doing.  Now that I see the expanded names of these parameters, it becomes much clearer to me what we're really doing here.

I know this approach isn't everyone's preference so I'd like to discuss it here if possible.

**Comment by MikeTheCanuck** [comment]
OK, so the work here is to expand the shortened flags in /bin/deploy.sh:
https://github.com/hackoregon/backend-examplar-2018/pull/60/files#diff-01dd223246b3d82a911250aceaac85b5

**Comment by nam20485** [comment]
Is this close-able now? Or are there still areas where we need to replace the shorthand command with the verbose ones?
