### ISSUE TITLE
Docker push fails due to failed "aws ecr get-login" command

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#58]
Last year's API projects all used the following code to authenticate to ECR and upload the newly-built docker image:

```
    echo Getting the ECR login...
    eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    echo Running docker push command...
    docker push "$DOCKER_REPO"/"$DEPLOY_TARGET"/"$DOCKER_IMAGE":latest
```

The [Travis logs](https://travis-ci.org/hackoregon/transportation-system-backend/builds/374749455) for a recent attempt at using this now in a 2018 API project, resulted in two new problems we've never seen before:

```
...
Getting the ECR login...
unknown shorthand flag: 'e' in -e
See 'docker login --help'.
...
```

Then later, as the `docker push` command attempts to write to the ECR repo:
`no basic auth credentials`

**Comment by znmeb** [comment]
Hmmm ... looks like it's not logging into the image repository - thats' $DOCKER_REPO. Is there a `docker login` somewhere before the push?

**Comment by MikeTheCanuck** [comment]
The `--no-include-email` flag definitely fixed this error.
