### ISSUE TITLE
Direction needed on travis deploy/build image/test changes

### ISSUE THREAD

**Issue by nam20485** [hackoregon/backend-examplar-2018#59]
See issue hackoregon/transportation-system-backend#46. I have travis.yml working well in my hackoregon/disaster-resilience-backend, do we want to merge those changes in to backend-exemplar, so that the generated quickstart app automatically works on travis. If so, when do we want to do that merge, given that the buildathon is less than two days away.

**Comment by znmeb** [comment]
Good question - I have no opinion on timing. My personal plan for the buildathon is to stay there until I get kicked out ;-). I'm working on two story cards, neither of which will depend on any backend / devops stuff during the buildathon. So I won't be available to test this till after the buildathon.

**Comment by MikeTheCanuck** [comment]
I would very much like a working, generalised .travis.yml in the exemplar to give everyone a head start at the CI feedback loop that was so critical last year.

I haven’t seen your Nathan and I didn’t consult anything but last year’s repos in the working file I added to the transportation-systems-backend last night (and then broke this morning).  It’s in a recent branch.

Nathan, if you feel up to pushing a PR to the exemplar that’s either your current file, or an amalgam of yours and mine, let’s get something on the table soon.  Thanks!

**Comment by nam20485** [comment]
I should have a PR created to share with you guys tonight or tomorrow
morning.

**Comment by MikeTheCanuck** [comment]
Looks like we're well underway.  Feel free to close this out at your comfort @nam20485

**Comment by nam20485** [comment]
Closing
