### ISSUE TITLE
create-app.sh errors after removal of api app

### ISSUE THREAD

**Issue by adpeters** [hackoregon/backend-examplar-2018#6]
In following the README for creating your own API I got an error running create-app.sh. After running bin/create-project.sh and creating a new project, the api app is removed, however it is referenced in INSTALLED_APPS after the example-settings have been copied into the new settings.py file. So when you run ./manage.py startapp api in bin/create-app.sh, it errors saying that the api app does not exist.

The obvious solution to this is not copying the example settings over to the new settings.py file until after the app is created. We could create another script for this, but I was also thinking maybe we should just combine create-project.sh and create-app.sh into a single file and run it all at once with the settings copy at the end? Are there cases where you would want to run create-project but not create-app? Any other thoughts on this?

**Comment by bhgrant8** [comment]
Good catch. I think you are correct, these could be combined. I originally had them separated because there were a few manual adjustments I was making in between these steps in an earlier version.  

Within the scope of our projects I think we can assume that one would be creating the project and app at the same time.

**Comment by bhgrant8** [comment]
Hey, yeah intention is to call the remove-sample.sh not repeat the code in two places so go for #1.

For second question, yeah being able to set and pull from a script is actually the preferred method. I wasn't sure if you could read a .env from a shell script directly, so if you can make that happen and just read the project name from there would be a great addition.

**Comment by znmeb** [comment]
we can close this, I think - the pull request #14 covers this.

**Comment by BrianHGrant** [comment]
Yup, I am AFK for a few hours,  feel free to close
