### ISSUE TITLE
Add .dockerignore

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#67]
@BrianHGrant @bhgrant8 this was something you mentioned somewhere - you have a good idea what to add?  Please fire up a quick PR if so.

**Comment by bhgrant8** [comment]
Something like the following should be adequate. Not sure where to make a commit to in the meantime.

This is based on:
https://github.com/docker/docker-py/blob/master/.dockerignore
https://github.com/sameersbn/docker-gitlab/blob/master/.dockerignore
https://codefresh.io/docker-tutorial/not-ignore-dockerignore/
https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/container_engine/django_tutorial/.dockerignore

```
.git
.cache
Dockerfile**
.gitignore
.env
*.MD
LICENSE
__pycache__
*.pyc
*.pyo
*.pyd
.Python
env
pip-log.txt
pip-delete-this-directory.txt
.tox
.coverage
.coverage.*
coverage.xml
*,cover
*.log
env.sample
```
