### ISSUE TITLE
Determine if we need the path voodoo in deploy.sh

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#68]
Last years' `docker-push.sh` scripts included a PATH declaration that added `$HOME/.local/bin`.

My best recollection is that this was necessary because we were installing **awscli** in the `.travis.yml`, and that from within the Travis environment it wasn't natively able to find the `aws` binary (which was installed in `--user` context).

It's being commented out for now, pending further evidence of its necessity:
https://github.com/hackoregon/backend-examplar-2018/pull/60/commits/6a1532500db59eca2670707a6c6a7ff5292ce44c

We ought to know that this is necessary if, during the Travis `deploy.sh` step, we see that the `aws ecr get-login` command fails.

There are three possibilities:
1. It's unnecessary for this year's architecture.
2. It's necessary and should be re-enabled as is.
3. It's necessary and should be re-enabled with whatever path the current non--user install is being performed here.

**Comment by nam20485** [comment]
I have the command commented out in my disaster-resilience-backend repo and the travis build has no problems calling the `aws ecr get-login`, it completes successfully. We  won't be able to verify this in the backend-examplar-2018 repo until after a fix is applied that allows the test.sh command to complete.

**Comment by MikeTheCanuck** [comment]
yep, this is confirmed in other repos too.  wish I'd figured this out last year.
