### ISSUE TITLE
Make sure all in-use env vars are represented in env.sample

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#77]
There are at least two "new" environment variables in play this year, that might or might not be relevant to local development usage:
https://github.com/hackoregon/backend-examplar-2018/issues/51#issuecomment-386836134 (comment entitled "New env vars in play this year").

There may be others that weren't captured, that are documented in this comment:
https://github.com/hackoregon/backend-examplar-2018/issues/51#issuecomment-385221942

**Comment by znmeb** [comment]
Can we close this? I think we have all the environment variables documented.

**Comment by nam20485** [comment]
Closing. All existing variables to-date are represented and comment added for description in the sample.env
