### ISSUE TITLE
Document the intended usage of each /bin script

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#8]
There are a great number of scripts in the `/bin` directory, some of which are only meant for use by developers for local development, others used in the build/test/deploy pipeline, and some that are only used inside the container (whether during CI or during production initialization of the containerized app).

It will help folks understand what's used by whom for what purpose.

Let's document this in the global README.md.

**Comment by bhgrant8** [comment]
I've assigned to myself for the moment. I did write most of them, hehe

**Comment by bhgrant8** [comment]
began writing these out

**Comment by znmeb** [comment]
Is this going to be a separate pull request or are you folding it into the https://github.com/hackoregon/backend-examplar-2018/pull/14?

**Comment by MikeTheCanuck** [comment]
FYI, I decided to do as I say so I wrote up a basic README for the `civic-devops` repo's `/bin` directory:
https://github.com/hackoregon/civic-devops/blob/master/bin/README.md
